[package]
name = "adventofcode-2021"
version = "0.1.0"
authors = []
rust-version = "1.56"
edition="2021"

[dependencies]

[[bin]]
name = "day-01-part-1-enizor"
path = "./day-01/part-1/enizor.rs"

[[bin]]
name = "day-01-part-2-enizor"
path = "./day-01/part-2/enizor.rs"
